$(document).ready(function(){
    $("#clothes").click(function(){
        $("#clot").css("display","block");
    });
    $("#t-shirt").click(function(){
        $("#t-sh").css("display","block");
    });
    $("#trouser").click(function(){
        $("#trou").css("display","block");
    });
    $("#electronics").click(function(){
        console.log("jbgsdcv");
        $("#elect").css("display","block");
    });
    $("#mobile").click(function(){
        console.log("jbgsdcv");
        $("#mob").css("display","block");
    });
    $("#tabs").click(function(){
        console.log("jbgsdcv");
        $("#ta").css("display","block");
    });
});